# Generated by Django 4.0.3 on 2022-03-27 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.FloatField()),
                ('deleted', models.BooleanField()),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                      parent_link=True, primary_key=True, serialize=False, to='stowdo_storage.resource')),
                ('creation_date', models.DateTimeField()),
                ('parent_folder', models.ForeignKey(default=None, null=True,
                                                    on_delete=django.db.models.deletion.CASCADE, to='stowdo_storage.folder')),
            ],
            bases=('stowdo_storage.resource',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                      parent_link=True, primary_key=True, serialize=False, to='stowdo_storage.resource')),
                ('path', models.FileField(default='', upload_to='')),
                ('upload_date', models.DateTimeField()),
                ('parent_folder', models.ForeignKey(default=None, null=True,
                                                    on_delete=django.db.models.deletion.CASCADE, to='stowdo_storage.folder')),
            ],
            bases=('stowdo_storage.resource',),
        ),
    ]
