# Generated by Django 4.0.1 on 2022-01-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_file_parent_folder_alter_folder_parent_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent_folder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.folder'),
        ),
    ]
