# Generated by Django 4.0.1 on 2022-01-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_file_parent_folder_alter_folder_parent_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
