# Generated by Django 4.0.1 on 2022-01-12 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='update_date',
            new_name='upload_date',
        ),
    ]
