# Generated by Django 4.0.1 on 2022-01-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_rename_update_date_file_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
